### ISSUE TITLE
AntiSandbox using DeviceIoControl

### ISSUE THREAD

**Issue by MerX1030** [brad-sp/cuckoomon-modified#12]
Was looking into some antisandbox technique and found this:
https://www.f-secure.com/weblog/archives/00002810.html

The first few techniques are covered by the recent cuckoomon.
The one using DeviceIoControl seems to have some issues.

My simple solution is to give a fake the OutBuffer result for a call to DeviceIoControl api with parameter IoControlCode = IOCTL_DISK_GET_DRIVE_GEOMETRY_EX

**Comment by brad-sp** [comment]
Are you sure you're using the latest version?  I just killed this and some related techniques just the other day (May 7th) and confirmed with that sample in the article.

**Comment by MerX1030** [comment]
Sorry. Just updated the day before that (May 6th).
Thanks!
