### ISSUE TITLE
Additional AntiVM

### ISSUE THREAD

**Issue by MerX1030** [brad-sp/cuckoomon-modified#13]
Could you add VBOX to the following code in misc.c:
    if (IoControlCode == IOCTL_STORAGE_QUERY_PROPERTY) {
        replace_string_in_buf(OutputBuffer, OutputBufferLength, "QEMU", "DELL");
        replace_string_in_buf(OutputBuffer, OutputBufferLength, "VMware", "DELL__");
        replace_string_in_buf(OutputBuffer, OutputBufferLength, "Virtual", "C300_BD");
                replace_string_in_buf(OutputBuffer, OutputBufferLength, "VBOX", "DELL");
    }       

I got the following results using current version:
DeviceIoControl DeviceHandle: 0x00000088 
OutBuffer: {hexvalues}VBOX HARDDISK 1.0 VBOX HARDDISK{hexvalues}
IoControlCode: IOCTL_STORAGE_QUERY_PROPERTY 
InBuffer: \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00

**Comment by brad-sp** [comment]
Done, thanks!

**Comment by MerX1030** [comment]
Thanks!
