### ISSUE TITLE
Process injection either causes crash or does not follow injected process

### ISSUE THREAD

**Issue by MerX1030** [brad-sp/cuckoomon-modified#14]
Sample for your reference:
http://cuckoo.killerinstinct.me/analysis/2142

I tried to run old samples that I tested previously and was surprised when I noticed that the results were different from before. This specific sample is a dyre malware which injects to svchost.exe.
Previously, it worked fine in old versions (modified April 6 9:09AM) of cuckoomon.
Checked the logs and noticed that during the part of injection where finds the process svchost.exe then injects its code there were some differences between using the old version of cuckoomon and the latest.

Old sequence of APIs:
NtMapViewOfSection
LdrGetDllHandle
LdrGetProcedureAddress
NtOpenThread
LdrGetDllHandle
LdrGetProcedureAddress
NtQueueApcThread
and so on

New sequence of APIs:
NtMapViewOfSection
LdrGetDllHandle
LdrGetProcedureAddress
NtQuerySystemInformation
NtClose
NtTerminateProcess
and so on

It failed to record NtOpenThread and NtQueueApcThread.

**Comment by brad-sp** [comment]
Looks like there's a crash in NtQuerySystemInformation -- fixing it now.

**Comment by brad-sp** [comment]
Should be fixed now, tested against the sample you linked.  Thanks for the report!

**Comment by MerX1030** [comment]
Many thanks too!
