### ISSUE TITLE
Repeated sequence of API calls causes a bloat in logs

### ISSUE THREAD

**Issue by MerX1030** [brad-sp/cuckoomon-modified#16]
http://cuckoo.killerinstinct.me/analysis/2166/#

Repeated junk calls using the pair NtOpenSection and NtWaitForSingleObject causes the size of the logs to blow up.
During some testing of other samples, I also noticed the other repeated junk calls using the pair NtDeleteFile and NtDelayExecution.
In essence any pair of API can be used.

**Comment by brad-sp** [comment]
or any sequence of calls really, not just pairs.  Unfortunately, there's only so much we can do to fix this since we resolve duplicates at the cuckoomon level.

**Comment by MerX1030** [comment]
Yeah, I agree. We can't possibly track all the permutations of sequence of feelers APIs a sample may call. Thanks!
