### ISSUE TITLE
APIs of remote threads aren't logged properly after latest commit.

### ISSUE THREAD

**Issue by MerX1030** [brad-sp/cuckoomon-modified#17]
I ran the same sample using the latest cuckoomon uploaded in cuckoo-modified and got very different results as compared with using the cuckoomon in commit cb53f9620754713c1e8031de18cc6d743ed17f80

Here's the sample's hash for your reference.
MD5 4a58c571d112513dc81b52e5c0962c37
SHA1    25da31c947cb61bd5fa9a0b9c8541bfbd70ed74a

**Comment by MerX1030** [comment]
Probably a problem in the process injection function as it was heavily revamped.

**Comment by brad-sp** [comment]
Can you explain the difference in results?  I have no problems with the hash you posted.  It's possible for some logs to be lost near the end of analysis if a process crashes, but that has to do with the reverting of the log flushing code.  I need to determine the cause of IE hanging with that code in place before I can add it back.

**Comment by MerX1030** [comment]
I'm using Windows XP virtual machine.
Here are the results:

Processtree looks like this:
sample.exe
    sample.exe
explorer.exe
    1.tmp
        1.tmp
    2.tmp
    3.tmp
        3.tmp

New DLL:
Processtree looks like this:
sample.exe
    sample.exe
explorer.exe

It seems that for the new DLL, the API logging stopped at VirtualProtectEx in explorer.exe just right before it should perform WriteProcessMemory.

Previous DLL:
![olddll](https://cloud.githubusercontent.com/assets/11789561/7887768/2433e1ea-05f9-11e5-88f9-a7897b29b2bf.png)

New DLL:
![newdll](https://cloud.githubusercontent.com/assets/11789561/7887767/2431cf7c-05f9-11e5-80bb-797d7d963177.png)
