### ISSUE TITLE
Anti-vm (Process32First and Process32Next)

### ISSUE THREAD

**Issue by ghost** [brad-sp/cuckoomon-modified#18]
Common malware get the list of running process and compare it to the list of process names. Once found, malware will not proceed with intended routine.

CreateToolhelp32Snapshot > Process32FirstW > Process32NextW
vmwareuser.exe  
vmwareservice.exe  
vboxservice.exe  
vboxtray.exe  
sandboxiedcomlaunch.exe  
sandboxierpcss.exe  
procmon.exe  
regmon.exe  
filemon.exe  
wireshark.exe  
netmon.exe  
prl_tools_service.exe (Parallels)  
prl_tools.exe (Parallels)  
prl_cc.exe (Parallels)  
sharedintapp.exe (Parallels)  
vmtoolsd.exe  
vmsrvc.exe  
vmusrvc.exe  
python.exe  
perl.exe

**Comment by brad-sp** [comment]
We already protect our own processes from discovery -- this is why you won't see python.exe in the list of running apps.  We could expand this list by having analyzer.py get the PID of each of those processes prior to running the malware and submit the active ones to the first cuckoomon instance.

**Comment by brad-sp** [comment]
The latest version now does exactly what I described above.
