### ISSUE TITLE
premature end of analysis

### ISSUE THREAD

**Issue by MerX1030** [brad-sp/cuckoomon-modified#26]
can't seem to find the root cause of the premature analysis for the following sample:

MD5:cb345ee48e811219387ffcd0d76788f2
SHA1:60a55ed53703dc7ea7df8429de90f0d5d0652ad5

Tried to debug this sample with OllyDbg and saw that there were some APIs it was supposed to do but was not logged by cuckoomon.

**Comment by brad-sp** [comment]
I've figured out the issue.  Thinking of the best solution, and then I'll post an analysis.

**Comment by brad-sp** [comment]
Thanks, fixed.
