### ISSUE TITLE
Process terminating prematurely

### ISSUE THREAD

**Issue by micomico14** [brad-sp/cuckoomon-modified#28]
Hi,
I have encountered some problem with the following sample:
MD5: f902e407243d62fced03376783f75683
SHA1: 5fc76c8bc0ca79f7b32363ae349a4d043457cf28

It didn't log any behavior but apparently, some HTTP activities were present but was not visible in behavior as if the process has terminated prematurely. 
Thanks

**Comment by brad-sp** [comment]
Looking into it, thanks.  Seems cuckoomon fails to load in the process.

-Brad

**Comment by brad-sp** [comment]
Should be fixed now, thanks for the report!

-Brad
