### ISSUE TITLE
Anti-VM by querying registry data in "HKEY_LOCAL_MACHINE\SYSTEM\ControlSet{number}\Services\Disk\Enum\0"

### ISSUE THREAD

**Issue by MerX1030** [brad-sp/cuckoomon-modified#4]
do we have anti-anti-vm solution for the following:

RegQueryValueEx the entry "HKEY_LOCAL_MACHINE\SYSTEM\ControlSet{number}\Services\Disk\Enum\0"
and check for the following strings:
_VIRTUAL_, _VMWARE_, _VBOX_, _QEMU_

Thanks!

**Comment by brad-sp** [comment]
We do now, thanks! https://github.com/brad-accuvant/cuckoomon-modified/commit/286c79882340b883db3ddd637b13ad81f42385a0 https://github.com/brad-accuvant/community-modified/commit/3141ad0dbdc9a501045e6226e62f3e81b299570f

**Comment by MerX1030** [comment]
So fast! Will let you know when something comes up again. :)
