### ISSUE TITLE
Monitored process "chcp.com" stuck

### ISSUE THREAD

**Issue by MerX1030** [brad-sp/cuckoomon-modified#8]
I don't know the proper term, but it seems like the process "chcp.com" was not monitored correctly and got stuck somewhere.
I also tried it in KillerInstinct's setup and had the same results:
-http://cuckoo.killerinstinct.me/analysis/1297

**Comment by brad-sp** [comment]
Yes, it's a known issue that I'm still working on debugging.  I need to build up a bit more testing infrastructure so I can debug the exact same circumstances.

**Comment by brad-sp** [comment]
It took a little while, but this should now be fixed.  I've overhauled the logging system to not depend on complex behaviors or separate logging threads, so any issues involving deadlocks should now be avoided (tested with the sample you provided).
